// clipboard-probe — reports pasteboard changes as JSON lines on stdout.
//
// Exists because Electron cannot see custom pasteboard types, which is where
// macOS applications declare that their contents are secret. Without this,
// a clipboard manager records what you copy out of a password manager.
//
// Two properties matter more than anything else here:
//
//   1. Concealed content never leaves this process. When a pasteboard item is
//      marked concealed or transient, the text is not read and not emitted —
//      only the fact that something private was copied. There is no path by
//      which it can reach the database, because it never reaches PHP.
//
//   2. Idle cost is a single integer comparison. NSPasteboard.changeCount is
//      just a counter; nothing is read until it moves. That is what makes it
//      safe to poll several times a second, which in turn shrinks the window
//      in which a quickly-replaced clip can be missed.
//
// Output, one JSON object per line:
//   {"change":42,"concealed":false,"app":"Safari","text":"…"}
//   {"change":43,"concealed":true,"app":"1Password"}          // no text, ever
//   {"change":44,"concealed":false,"app":"Xcode","oversize":true}

import AppKit
import Foundation

// https://nspasteboard.org — the convention password managers follow.
let concealedTypes: Set<String> = [
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
]

struct Options {
    var intervalMilliseconds: UInt32 = 150
    var maxBytes: Int = 2_000_000

    static func parse(_ arguments: [String]) -> Options {
        var options = Options()
        var index = 1

        while index < arguments.count {
            let flag = arguments[index]
            let value = index + 1 < arguments.count ? arguments[index + 1] : nil

            switch flag {
            case "--interval-ms":
                if let value, let parsed = UInt32(value), parsed >= 10 {
                    options.intervalMilliseconds = parsed
                }
                index += 2
            case "--max-bytes":
                if let value, let parsed = Int(value), parsed > 0 {
                    options.maxBytes = parsed
                }
                index += 2
            default:
                index += 1
            }
        }

        return options
    }
}

/// Hand-built so a pathological clip cannot produce invalid JSON, and so the
/// text field is assembled only when we have already decided it may be shared.
func encode(_ fields: [(String, String)]) -> String {
    "{" + fields.map { "\"\($0.0)\":\($0.1)" }.joined(separator: ",") + "}"
}

func jsonString(_ value: String) -> String {
    let data = try? JSONSerialization.data(withJSONObject: [value], options: [])

    guard let data, var encoded = String(data: data, encoding: .utf8) else {
        return "\"\""
    }

    encoded.removeFirst()   // [
    encoded.removeLast()    // ]

    return encoded
}

func emit(_ line: String) {
    // Line-buffered by hand: the reader is a polling PHP process that must see
    // each change as it happens, not when a buffer happens to fill.
    if let data = (line + "\n").data(using: .utf8) {
        FileHandle.standardOutput.write(data)
    }
}

let options = Options.parse(CommandLine.arguments)
let pasteboard = NSPasteboard.general
var lastChangeCount = pasteboard.changeCount

// Report whatever is already on the pasteboard at startup, so a watcher that
// restarts does not have to wait for the next copy to learn the current state.
var isFirstPass = true

while true {
    let changeCount = pasteboard.changeCount

    if changeCount != lastChangeCount || isFirstPass {
        lastChangeCount = changeCount
        isFirstPass = false

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        let isConcealed = !types.isDisjoint(with: concealedTypes)
        let app = NSWorkspace.shared.frontmostApplication?.localizedName

        var fields: [(String, String)] = [
            ("change", String(changeCount)),
            ("concealed", isConcealed ? "true" : "false"),
        ]

        if let app {
            fields.append(("app", jsonString(app)))
        }

        if isConcealed {
            // Deliberately no read: the point is that this text never exists
            // outside the application that owns it.
            emit(encode(fields))
        } else if let text = pasteboard.string(forType: .string) {
            if text.utf8.count > options.maxBytes {
                fields.append(("oversize", "true"))
            } else {
                fields.append(("text", jsonString(text)))
            }

            emit(encode(fields))
        } else {
            // A change with no text at all — an image or a file, which this
            // clipboard manager does not handle. Reported so the reader can
            // keep its change counter in step.
            emit(encode(fields))
        }
    }

    usleep(options.intervalMilliseconds * 1000)
}
